<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>SEND EMAIL</title>
        <style>
            * {
                margin: 0;
                box-sizing: border-box;
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
            }

            body
            { background-color: rgb(241, 227, 227); }

            #center
            {
                display: block;
                margin: 4rem auto;
                padding-top: 3rem;
                padding-left: 3rem;
                padding-right: 3rem;
                width: 90%;
                height: auto;
                background-color: #fff;
                box-shadow: 0px 0px 3px rgba(0,0,0,0.1);
            }

            #sender-brand
            {
                padding: 1rem 0;
                text-align: center;
                margin-bottom: 2rem;
            }

            #wrapper
            {
                display: block;
                margin: 0 auto;
                max-width: 90%;
            }

            #todo-title {
                font-size: 2rem;
                margin: 1rem 0;
            }

            #mailcontent, #todo-body
            {
                font-size: 1.20rem;
                overflow-wrap: break-word;
            }
            #todo-body {
                text-align: justify;
            }

            #footer {
                margin-top: 200px;
                padding: 2rem 0;
                background-color: rgb(175, 126, 126);
                text-align: center;
                color: #fff;
            }

            @media screen and (max-width: 576px)
            {
                #wrapper
                {
                    max-width: 100%;
                }
            }
        </style>
    </head>
    <body>
        <div id="center">
            <h1 id="sender-brand">TodoHero</h1>
            <div id="wrapper">
                <p id="mailcontent">
                    Hello {{ $user_todo_details->name }}, this message is automatically generated by TodoHeroApp.
                </p>
                <h3 id="todo-title">{{ $user_todo_details->title }}</h3>
                <p id="todo-body">{{ $user_todo_details->description }}</p>
            </div>
            <footer id="footer">
                <span class="small">© Copyright TodoHeroApp by andydevs69420 2022 All Rights Reserved</span>
            </footer>
        </div>
    </body>
</html>
